name: flutterando_web
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  animated_card: any
  rxdart: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  pedantic: any

flutter:
  uses-material-design: true


dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

  animated_card:
    git:
      url: https://github.com/davidsdearaujo/animated_card
      ref: web