name: flutterando_web
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  animated_card: any
  rxdart: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
    

flutter:
  uses-material-design: true
assets:
  - assets/images/logo.png
  - assets/images/team/alvaro.jpg
  - assets/images/team/bwolf.jpg
  - assets/images/team/david.jpg
  - assets/images/team/gabriel.jpg
  - assets/images/team/jacob.jpg
  - assets/images/team/matheus.jpg
  - assets/images/team/rully.jpg
  - assets/images/team/jacob_.jpg
  - assets/images/vectorpaint.png

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
      
  animated_card:
    git:
      url: https://github.com/davidsdearaujo/animated_card
      ref: web
